<?php
/**
 * Rameera_Email
 *
 * @category  MageMatch
 * @package   Rameera\Email
 * @author    MageMatch <arjundhiman90@gmail.com>
 * @copyright 2024 MageMatch
 * @license   MIT
 */
// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <table
      cellpadding="0"
      cellspacing="0"
      class="es-content"
      align="center"
    >
      <tbody>
        <tr>
          <td class="esd-stripe" align="center">
            <table
              bgcolor="#ffffff"
              class="es-content-body"
              align="center"
              cellpadding="0"
              cellspacing="0"
              width="600"
            >
              <tbody>
                <tr>
                  <td
                    class="esd-structure es-p30t es-p20r es-p20l esdev-adapt-off"
                    align="left"
                  >
                    <table
                      width="560"
                      cellpadding="0"
                      cellspacing="0"
                      class="esdev-mso-table"
                    >
                      <tbody>
                        <tr>
                          <td class="esdev-mso-td" valign="top">
                            <table
                              cellpadding="0"
                              cellspacing="0"
                              class="es-left"
                              align="left"
                            >
                              <tbody>
                                <tr>
                                  <td
                                    width="280"
                                    align="left"
                                    class="esd-container-frame"
                                  >
                                    <table
                                      cellpadding="0"
                                      cellspacing="0"
                                      width="100%"
                                    >
                                      <tbody>
                                        <tr>
                                          <td
                                            align="left"
                                            class="esd-block-text es-p5t es-p5b es-p10l"
                                            bgcolor="#E8EAED"
                                          >
                                            <p
                                              style="
                                                font-size: 16px;
                                                color: #1d1f22;
                                              "
                                            >
                                              <?= $block->escapeHtml(__('Item')) ?>
                                            </p>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                          <td class="esdev-mso-td" valign="top">
                            <table
                              cellpadding="0"
                              cellspacing="0"
                              class="es-left"
                              align="left"
                            >
                              <tbody>
                                <tr>
                                  <td
                                    width="140"
                                    align="left"
                                    class="esd-container-frame"
                                  >
                                    <table
                                      cellpadding="0"
                                      cellspacing="0"
                                      width="100%"
                                    >
                                      <tbody>
                                        <tr>
                                          <td
                                            align="left"
                                            class="esd-block-text es-p5t es-p5b es-p10l"
                                            bgcolor="#E8EAED"
                                          >
                                            <p
                                              style="
                                                font-size: 16px;
                                                color: #1d1f22;
                                              "
                                            >
                                              <?= $block->escapeHtml(__('Quantity')) ?>
                                            </p>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                          <td class="esdev-mso-td" valign="top">
                            <table
                              cellpadding="0"
                              cellspacing="0"
                              class="es-right"
                              align="right"
                            >
                              <tbody>
                                <tr>
                                  <td
                                    width="140"
                                    align="left"
                                    class="esd-container-frame"
                                  >
                                    <table
                                      cellpadding="0"
                                      cellspacing="0"
                                      width="100%"
                                    >
                                      <tbody>
                                        <tr>
                                          <td
                                            align="right"
                                            class="esd-block-text es-p5t es-p5b es-p10r es-p10l"
                                            bgcolor="#E8EAED"
                                          >
                                            <p
                                              style="
                                                font-size: 16px;
                                                color: #1d1f22;
                                              "
                                            >
                                              <?= $block->escapeHtml(__('Amount')) ?>
                                            </p>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>

    <?php $_items = $_order->getAllItems(); ?>
    <?php foreach ($_items as $_item) : ?>
        <?php if (!$_item->getParentItem()) : ?>
            <?= $block->getItemHtml($_item) ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?= $block->getChildHtml('order_totals') ?>
<?php endif; ?>
